---
- hosts: all
  become: true
  
  tasks:
  - name: install wget
    yum:
      name: wget
      state: latest
  - name: download node exporter
    shell: cd /tmp/ && wget https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
