- hosts: localhost
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=ansible_facts
    - name: upgrade software on {{inventory_hostname}}
    - name: current host is {{ansible_hostname}}
    
    - name: Update IP address to tmp file
      shell: echo {{ ansible_default_ipv4.address }}  >> /tmp/hosts.test
