---
- hosts: all
  become: true
  
  tasks:
  - name: Update IP address to tmp file
    shell: export IDMPASS="";/sbin/ipa-client-install -p hostadmin --enable-dns-updates --mkhomedir -w ${IDMPASS} -U --force-join

