- hosts: all
  tasks:
  - name: Update IP address to tmp file
    shell: export IDMPASS="BzedSCmzNXU}:s[@jM'p";ipa-client-install -p hostadmin --enable-dns-updates --mkhomedir -w ${IDMPASS} -U --force-join

