- hosts: all
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=ansible_facts
    - name: Update IP address to tmp file
      shell: " echo {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address']}} "  >> /tmp/hosts.test

