---
- hosts: all
  tasks:
    - name: Install  WMI_Exporter to send OS level Metric to Prometheus 
      win_msi:
        path: https://github.com/martinlindhe/wmi_exporter/releases/download/v0.5.0/wmi_exporter-0.5.0-amd64.msi
        state: present
        extra_args: ENABLED_COLLECTORS=os,service LISTEN_PORT=9182
